<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace hrzg\widget\models\crud\base;

use hrzg\widget\models\crud\query\WidgetPageTranslationQuery;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "app_hrzg_widget_page_translation".
 *
 * @property integer $id
 * @property integer $widget_page_id
 * @property string $language
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \hrzg\widget\models\crud\WidgetPage $widgetPage
 * @property string $aliasModel
 */
abstract class WidgetPageTranslation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%hrzg_widget_page_translation}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()')
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['widget_page_id', 'language', 'title'], 'required'],
            [['widget_page_id'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['title'], 'string', 'max' => 128],
            [['description', 'keywords'], 'string', 'max' => 255],
            [['widget_page_id', 'language'], 'unique', 'targetAttribute' => ['widget_page_id', 'language']],
            [['widget_page_id'], 'exist', 'skipOnError' => true, 'targetClass' => \hrzg\widget\models\crud\WidgetPage::className(), 'targetAttribute' => ['widget_page_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('widgets', 'ID'),
            'widget_page_id' => Yii::t('widgets', 'Widget Page ID'),
            'language' => Yii::t('widgets', 'Language'),
            'title' => Yii::t('widgets', 'Title'),
            'description' => Yii::t('widgets', 'Description'),
            'keywords' => Yii::t('widgets', 'Keywords'),
            'created_at' => Yii::t('widgets', 'Created At'),
            'updated_at' => Yii::t('widgets', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWidgetPage()
    {
        return $this->hasOne(\hrzg\widget\models\crud\WidgetPage::class, ['id' => 'widget_page_id']);
    }


    
    /**
     * @inheritdoc
     * @return WidgetPageTranslationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new WidgetPageTranslationQuery(static::class);
    }


}
