<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace hrzg\widget\models\crud\base;

use hrzg\widget\models\crud\query\WidgetPageMetaQuery;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "hrzg_widget_page_meta".
 *
 * @property integer $id
 * @property integer $widget_page_id
 * @property string $language
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \hrzg\widget\models\crud\WidgetPage $widgetPage
 * @property string $aliasModel
 */
abstract class WidgetPageMeta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%hrzg_widget_page_meta}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['widget_page_id', 'language'], 'required'],
            [['widget_page_id', 'status'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['widget_page_id', 'language'], 'unique', 'targetAttribute' => ['widget_page_id', 'language']],
            [['widget_page_id'], 'exist', 'skipOnError' => true, 'targetClass' => \hrzg\widget\models\crud\WidgetPage::class, 'targetAttribute' => ['widget_page_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('widgets', 'ID'),
            'widget_page_id' => Yii::t('widgets', 'Widget Page ID'),
            'language' => Yii::t('widgets', 'Language'),
            'status' => Yii::t('widgets', 'Status'),
            'created_at' => Yii::t('widgets', 'Created At'),
            'updated_at' => Yii::t('widgets', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWidgetPage()
    {
        return $this->hasOne(\hrzg\widget\models\crud\WidgetPage::class, ['id' => 'widget_page_id']);
    }


    
    /**
     * @inheritdoc
     * @return WidgetPageMetaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new WidgetPageMetaQuery(static::class);
    }


}
