<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace hrzg\widget\models\crud\base;

use Yii;

/**
 * This is the base-model class for table "app_hrzg_widget_template".
 *
 * @property integer $id
 * @property string $name
 * @property string $json_schema
 * @property string $twig_template
 */
abstract class WidgetTemplate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'app_hrzg_widget_template';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('app', 'WidgetTemplates');
        }else{
            return Yii::t('app', 'WidgetTemplate');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'json_schema'], 'required'],
            [['json_schema', 'twig_template'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'json_schema' => Yii::t('app', 'Json Schema'),
            'twig_template' => Yii::t('app', 'Template'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'json_schema' => Yii::t('app', 'Json Schema'),
            'twig_template' => Yii::t('app', 'Template'),
            ]);
    }


    
    /**
     * @inheritdoc
     * @return \hrzg\widget\models\crud\query\WidgetTemplateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \hrzg\widget\models\crud\query\WidgetTemplateQuery(get_called_class());
    }


}
