<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace hrzg\widget\models\crud\base;

use Yii;

/**
 * This is the base-model class for table "app_hrzg_widget".
 *
 * @property int $id
 * @property string $status
 * @property string $widget_template_id
 * @property string $default_properties_json
 * @property string $name_id
 * @property string $container_id
 * @property string $rank
 * @property string $route
 * @property string $request_param
 * @property string $access_owner
 * @property string $access_domain
 * @property string $access_read
 * @property string $access_update
 * @property string $access_delete
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Widget extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'app_hrzg_widget_content';
    }

    /**
     * {@inheritdoc}
     *
     * @return \hrzg\widget\models\crud\query\WidgetQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \hrzg\widget\models\crud\query\WidgetQuery(get_called_class());
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later.
     *
     * @return string
     */
    public function getAliasModel($plural = false)
    {
        if ($plural) {
            return Yii::t('app', 'Widgets');
        } else {
            return Yii::t('app', 'Widget');
        }
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'widget_template_id', 'container_id', 'route'], 'required'],
            [['default_properties_json'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['status'], 'string', 'max' => 32],
            [['widget_template_id', 'container_id', 'route'], 'string', 'max' => 128],
            [['name_id'], 'string', 'max' => 64],
            [['rank', 'access_owner'], 'string', 'max' => 11],
            [['request_param', 'access_read', 'access_update', 'access_delete'], 'string', 'max' => 255],
            [['access_domain'], 'string', 'max' => 8],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'status' => Yii::t('app', 'Status'),
            'widget_template_id' => Yii::t('app', 'Template'),
            'default_properties_json' => Yii::t('app', 'Widget Properties'),
            'name_id' => Yii::t('app', 'Name ID'),
            'container_id' => Yii::t('app', 'Container ID'),
            'rank' => Yii::t('app', 'Rank'),
            'route' => Yii::t('app', 'Route'),
            'request_param' => Yii::t('app', 'Request Param'),
            'access_owner' => Yii::t('app', 'Access Owner'),
            'access_domain' => Yii::t('app', 'Access Domain'),
            'access_read' => Yii::t('app', 'Access Read'),
            'access_update' => Yii::t('app', 'Access Update'),
            'access_delete' => Yii::t('app', 'Access Delete'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /*
     * @inheritdoc
     */
    /*public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
                'id' => Yii::t('app', 'ID'),
                'status' => Yii::t('app', 'Status'),
                'widget_template_id' => Yii::t('app', 'Class Name'),
                'default_properties_json' => Yii::t('app', 'Default Properties Json'),
                'name_id' => Yii::t('app', 'Name Id'),
                'container_id' => Yii::t('app', 'Container Id'),
                'rank' => Yii::t('app', 'Rank'),
                'route' => Yii::t('app', 'Route'),
                'request_param' => Yii::t('app', 'Request Param'),
                'access_owner' => Yii::t('app', 'Access Owner'),
                'access_domain' => Yii::t('app', 'Access Domain'),
                'access_read' => Yii::t('app', 'Access Read'),
                'access_update' => Yii::t('app', 'Access Update'),
                'access_delete' => Yii::t('app', 'Access Delete'),
                'created_at' => Yii::t('app', 'Created At'),
                'updated_at' => Yii::t('app', 'Updated At'),
            ]);
    }*/
}
